# Generated by Django 3.0b1 on 2019-11-13 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='team_logos/')),
                ('team_admin', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('headshot', models.ImageField(upload_to='worker_images/')),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('availability', models.CharField(choices=[('FTR', 'Full-time, Regular hours'), ('FTI', 'Full-time, Irregular hours (nights, weekends)'), ('PTR', 'Part-time, Regular hours (most nights, weekends)'), ('PTI', 'Part-time, Irregular hours (here and there)'), ('NA', 'Not Currently Available, Just staying informed')], default='FTR', max_length=3)),
                ('min_hourly_rate', models.IntegerField(max_length=3)),
                ('skills', models.TextField(max_length=500)),
                ('headline', models.CharField(max_length=255)),
                ('referred_by', models.CharField(max_length=255)),
                ('references', models.TextField(max_length=1000)),
                ('referred_to', models.TextField(blank=True, max_length=500)),
                ('comments', models.TextField(blank=True, max_length=500)),
                ('sign_up_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('connections', models.ManyToManyField(blank=True, related_name='_worker_connections_+', to='copro_profiles.Worker')),
                ('teams', models.ManyToManyField(related_name='workers', to='copro_profiles.Team')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('screenshot', models.ImageField(upload_to='link_screenshots')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_links', to='copro_profiles.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.TextField(max_length=1000)),
                ('screenshot', models.ImageField(upload_to='link_screenshots')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_links', to='copro_profiles.Worker')),
            ],
        ),
    ]
