# Generated by Django 2.2.7 on 2019-12-04 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, upload_to='staticfiles/admin/img/team_logos/')),
                ('description', models.CharField(max_length=255)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone', models.CharField(max_length=20)),
                ('headshot', models.ImageField(blank=True, upload_to='staticfiles/admin/img/worker_images/')),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='USA', max_length=100)),
                ('availability', models.CharField(choices=[('FTR', 'Full-time, Regular hours'), ('FTI', 'Full-time, Irregular hours (nights, weekends)'), ('PTR', 'Part-time, Regular hours (most nights, weekends)'), ('PTI', 'Part-time, Irregular hours (here and there)'), ('NA', 'Not Currently Available, Just staying informed')], default='FTR', max_length=3)),
                ('min_hourly_rate', models.IntegerField()),
                ('skills', models.TextField(max_length=500)),
                ('headline', models.CharField(max_length=255)),
                ('referred_by', models.CharField(max_length=255)),
                ('references', models.TextField(max_length=1000)),
                ('referred_to', models.TextField(blank=True, max_length=500)),
                ('comments', models.TextField(blank=True, max_length=500)),
                ('sign_up_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('connections', models.ManyToManyField(blank=True, related_name='_worker_connections_+', to='copro_profiles.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.URLField(max_length=1000)),
                ('screenshot', models.ImageField(blank=True, upload_to='staticfiles/admin/img/link_screenshots')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_links', to='copro_profiles.Worker')),
            ],
        ),
        migrations.CreateModel(
            name='TeamLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('url', models.TextField(max_length=1000)),
                ('screenshot', models.ImageField(blank=True, upload_to='staticfiles/admin/img/link_screenshots')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('updated_date', models.DateField(auto_now=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_links', to='copro_profiles.Team')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='team_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='copro_profiles.Worker'),
        ),
    ]
