# Generated by Django 3.0b1 on 2019-11-18 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copro_profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='user_worker_id',
        ),
        migrations.AddField(
            model_name='worker',
            name='worker_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
