# Generated by Django 3.0b1 on 2019-11-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copro_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='min_hourly_rate',
            field=models.IntegerField(),
        ),
    ]
