# Generated by Django 3.0b1 on 2019-11-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro_profiles', '0002_auto_20191118_1622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='worker_id',
        ),
    ]
