# Generated by Django 3.0b1 on 2019-11-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('copro_profiles', '0003_auto_20191113_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='teams',
        ),
        migrations.AlterField(
            model_name='team',
            name='team_admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='copro_profiles.Worker'),
        ),
    ]
