# Generated by Django 3.0b1 on 2019-11-18 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro_profiles', '0003_auto_20191118_1627'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='user_id',
            new_name='username',
        ),
    ]
