# Generated by Django 3.0b1 on 2019-11-18 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('copro_profiles', '0004_auto_20191118_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_id',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
