# Generated by Django 3.0b1 on 2019-11-18 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copro_profiles', '0005_worker_worker_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='worker',
            old_name='username',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='worker_id',
        ),
    ]
